#include "ModuleRegistry.hpp"

// canonical ids over existing storage; toggling here equals mod.json.

namespace paimon::modules {

namespace {

using S = Section;
using B = Backing;

constexpr char const* kThumbs = "paimbnails.thumbnails.browser";
constexpr char const* kInfoSuite = "paimbnails.infosuite.info";
constexpr char const* kPerformance = "paimbnails.performance.gameplay";
constexpr char const* kIconGradients = "paimbnails.icongradients.global";
constexpr char const* kNone = "";

Module setting(char const* id, char const* name, char const* desc, char const* key,
               char const* group, S section, bool defaultOn, char const* parent = kNone) {
    return {id, name, desc, key, parent, group, section, B::Setting, defaultOn};
}

Module saved(char const* id, char const* name, char const* desc, char const* key,
             char const* group, S section, bool defaultOn, char const* parent = kNone) {
    return {id, name, desc, key, parent, group, section, B::Saved, defaultOn};
}

Module custom(char const* id, char const* name, char const* desc, char const* group,
              S section, bool defaultOn, char const* parent = kNone) {
    return {id, name, desc, kNone, parent, group, section, B::Custom, defaultOn};
}

Module infoMod(char const* id, char const* name, char const* desc, char const* key,
               char const* group, bool defaultOn, char const* parent = kInfoSuite) {
    return {id, name, desc, key, parent, group, S::Info, B::Setting, defaultOn};
}

std::vector<Module> buildCatalog() {
    return {
        // Interface — active everywhere
        setting("paimbnails.smoothui.global", "Smooth UI",
                "Eased popup transitions and button presses.",
                "smooth-ui-enabled", "Motion", S::Global, true),
        setting("paimbnails.dynamicpopups.global", "Dynamic Popups",
                "Enter and exit animations on every popup.",
                "dynamic-popup-enabled", "Motion", S::Global, true),
        setting("paimbnails.popupblur.global", "Popup Blur",
                "Blurs the scene behind popups.",
                "popup-blur-enabled", "Motion", S::Global, true),
        setting("paimbnails.smoothscroll.global", "Smooth Scroll",
                "Inertial mouse wheel scrolling in menus and lists.",
                "smooth-scroll", "Input", S::Global, true),
        setting("paimbnails.smoothtext.global", "Smooth Text Input",
                "Animated letters while typing.",
                "smooth-text-enabled", "Motion", S::Global, false),
        setting("paimbnails.cursor.global", "Custom Cursor",
                "Replaces the system cursor with your own images.",
                "custom-cursor-enable", "Input", S::Global, false),
        custom("paimbnails.cursortransition.global", "Cursor Transitions",
               "Animated changes between cursor states.", "Motion", S::Global, true,
               "paimbnails.cursor.global"),
        custom("paimbnails.cursorclick.global", "Cursor Click Effects",
               "Bursts, hold effects and sounds when you click.", "Motion", S::Global,
               false, "paimbnails.cursor.global"),
        setting("paimbnails.customhover.global", "Custom Hover",
                "Custom button hover animations. Ctrl+click to edit; Ctrl+D to link all.",
                "custom-hover-enabled", "Motion", S::Global, false),
        setting("paimbnails.customslider.global", "Custom Slider Thumb",
                "Uses your icon as the slider thumb.",
                "custom-slider-enabled", "Skin", S::Global, false),
        setting("paimbnails.paimonicons.global", "Paimon Icons",
                "Recolors game icons with your palette.",
                "colorful-icons-enabled", "Skin", S::Global, true),
        custom("paimbnails.transitions.global", "Scene Transitions",
               "Custom transitions between scenes.", "Motion", S::Global, true),
        saved("paimbnails.volumescroll.global", "Volume Scroll",
              "Hold a modifier and scroll to change volume. On touch screens, drag with three fingers instead.",
              "module-volume-scroll", "Input", S::Global, true),
        saved("paimbnails.dynamicvolume.global", "Dynamic Volume",
              "Eases a loud song in at the previous track's level, or holds every song at one level.",
              "module-dynamic-volume", "Audio", S::Global, true),
        saved("paimbnails.safedrop.global", "Safe Drop",
              "Catches sudden effect and loudness spikes before they hit.",
              "module-safe-drop", "Audio", S::Global, true,
              "paimbnails.dynamicvolume.global"),
        saved("paimbnails.backgrounds.global", "Custom Backgrounds",
              "Images, videos and shaders as layer backgrounds.",
              "module-backgrounds", "Skin", S::Global, true),
        saved("paimbnails.beatshaders.global", "Beat Shaders",
              "Shader effects synced to the music beat.",
              "module-beat-shaders", "Skin", S::Global, true),
        custom("paimbnails.rtx.global", "Paimon RTX",
               "Screen-space traced lighting, occlusion and reflections over the whole game.",
               "Skin", S::Global, false),
        saved("paimbnails.quickhub.global", "Quick Hub",
              "Radial shortcut menu bound to a key or hold.",
              "module-quick-hub", "Shortcuts", S::Global, true),
        saved("paimbnails.separatedual.global", "Separate Dual Icons",
              "Customize the 2nd player's icons, colors, trails and death effect.",
              "module-separatedual", "Gameplay", S::Global, true),
        setting(kIconGradients, "Icon Gradients",
                "Custom gradient colors on your icons in the garage, menus and gameplay.",
                "icon-gradients-enabled", "Skin", S::Global, true),
        custom("paimbnails.gradientanimation.global", "Gradient Animations",
               "Animated movement for every icon gradient.", "Motion", S::Global, true,
               kIconGradients),

        saved("paimbnails.settingspanel.menu", "Settings Panel",
              "In-game settings panel with live previews.",
              "module-settings-panel", "Core", S::Menu, true),
        setting("paimbnails.menumusic.menu", "Menu Music Player",
                "Vinyl button with your library and playlists.",
                "menuMusicEnable", "Audio", S::Menu, true),
        saved("paimbnails.musiceffects.menu", "Menu Music Effects",
              "Speed, EQ, spatial sound, reverb and echo for Menu Music.",
              "module-musiceffects", "Audio", S::Menu, false,
              "paimbnails.menumusic.menu"),
        saved("paimbnails.spatialaudio.menu", "Spatial Audio",
              "Virtual stage, room depth and moving sound for Menu Music.",
              "menu-music-spatial-enabled", "Audio", S::Menu, false,
              "paimbnails.musiceffects.menu"),
        saved("paimbnails.menuloop.menu", "Menu Loop Control",
              "Now playing card, hotkeys and menu loop tools.",
              "module-menu-loop", "Audio", S::Menu, true),
        setting("paimbnails.menuloopshuffle.menu", "Menu Loop Shuffle",
                "Rotates the menu loop when a song ends.",
                "menuLoopConstantShuffle", "Audio", S::Menu, false,
                "paimbnails.menuloop.menu"),
        setting("paimbnails.menuphysics.menu", "Menu Physics",
                "Menu buttons gain gravity, spin and bounce.",
                "menu-physics-enable", "Layout", S::Menu, false),
        saved("paimbnails.menulayout.menu", "Layout Editor",
              "Move and restyle main menu and pause buttons.",
              "module-menu-layout", "Layout", S::Menu, true),
        custom("paimbnails.pet.menu", "Paimon Pet",
               "A pet that follows your cursor across layers.", "Companion", S::Menu, false),
        custom("paimbnails.guide.menu", "Paimon Guide",
               "In-game assistant that answers mod questions.", "Companion", S::Menu, true),
        saved("paimbnails.hiddenpaimon.menu", "Hidden Paimon",
              "Paimon hides under a random main menu button. With the Guide on she waits at the Paimon Hub button instead.",
              "module-hidden-paimon", "Companion", S::Menu, true),
        saved("paimbnails.paidraw.menu", "PaiDraw",
              "Collaborative drawing canvas.",
              "module-paidraw", "Tools", S::Menu, true),
        setting("paimbnails.iconmaker.menu", "Icon Maker",
                "Build and apply custom icons.",
                "icon-maker-enabled", "Tools", S::Menu, true),
        setting("paimbnails.texturestudio.menu", "Texture Studio",
                "Texture pack generator.",
                "texture-studio-enabled", "Tools", S::Menu, true),
        saved("paimbnails.devtools.menu", "Dev Tools",
              "GIF to sprite sheet converter and helpers.",
              "module-dev-tools", "Tools", S::Menu, true),
        saved("paimbnails.community.menu", "Community Hub",
              "Community leaderboard and history.",
              "module-community", "Community", S::Menu, true),
        saved("paimbnails.forum.menu", "Forum",
              "In-game posts and replies.", "module-forum", "Community", S::Menu, true),
        saved("paimbnails.versus.menu", "Versus",
              "Ranked 1v1 duels over Globed, from the Versus button.",
              "module-versus", "Community", S::Menu, true),
        saved("paimbnails.versus.hud", "Versus HUD",
              "Duel bars, card hand and active effects while playing a match.",
              "module-versus-hud", "Community", S::Menu, true,
              "paimbnails.versus.menu"),
        saved("paimbnails.versus.cards", "Versus Cards",
              "The Roulette deck. Off means the format is hidden from the queue.",
              "module-versus-cards", "Community", S::Menu, true,
              "paimbnails.versus.menu"),
        setting("paimbnails.twitchrequests.menu", "Level Requests",
                "Level requests from the web and live chats.",
                "twitch-requests-enabled", "Community", S::Menu, false),
        setting("paimbnails.webrequests.menu", "Web Requests",
                "Accept levels from flozwer.org/request/<username>.",
                "twitch-requests-web-enabled", "Community", S::Menu, false,
                "paimbnails.twitchrequests.menu"),
        setting("paimbnails.streamoverlay.menu", "OBS Stream Overlay",
                "Current level and request queue at a local OBS browser URL.",
                "twitch-requests-obs-enabled", "Community", S::Menu, false,
                "paimbnails.twitchrequests.menu"),
        setting("paimbnails.modpreviews.menu", "Mod Previews",
                "Preview images for Geode mods.",
                "mod-previews-enable", "Tools", S::Menu, true),

        saved(kThumbs, "Level Thumbnails",
              "Thumbnails on level cells, lists and leaderboards.",
              "module-thumbnails", "Core", S::Browser, true),
        setting("paimbnails.hovereffects.browser", "Hover Effects",
                "Animates level cells under the cursor.",
                "levelcell-hover-effects", "Core", S::Browser, true, kThumbs),
        setting("paimbnails.compactlist.browser", "Compact Mode",
                "Shorter cells to fit more levels.",
                "compact-list-mode", "Core", S::Browser, true, kThumbs),
        setting("paimbnails.autopreview.browser", "Auto Previews",
                "Renders a preview for levels with no thumbnail.",
                "auto-preview-enable", "Core", S::Browser, true, kThumbs),
        saved("paimbnails.levelthumbs.browser", "LevelThumbs Fallback",
              "Falls back to the Level Thumbnails database when a level has no Paimbnails thumbnail.",
              "module-levelthumbs", "Core", S::Browser, true, kThumbs),
        saved("paimbnails.leaderboardcells.browser", "Leaderboard Cells",
              "Custom layout and effects on score cells.",
              "module-scorecell", "Layout", S::Browser, true),
        saved("paimbnails.scoregradient.browser", "Score Gradient",
              "Icon-colored gradients on score cells with smooth hover animation.",
              "module-score-gradient", "Layout", S::Browser, false),
        setting("paimbnails.searchpreview.browser", "Realtime Search",
                "Results while you type in the search box.",
                "realtime-search-preview", "Search", S::Browser, false),
        saved("paimbnails.quicksearch.browser", "Quick Search",
              "Jump straight to a level id from the browser.",
              "module-quick-search", "Search", S::Browser, true),
        saved("paimbnails.searchhistory.browser", "Search History",
              "Remembers and suggests past searches.",
              "module-search-history", "Search", S::Browser, true),
        setting("paimbnails.incognito.browser", "Incognito Mode",
                "Stops saving and hides the search history.",
                "incognito-mode", "Search", S::Browser, false,
                "paimbnails.searchhistory.browser"),
        saved("paimbnails.foryou.browser", "For You",
              "Recommends levels from what you play.",
              "module-foryou", "Search", S::Browser, true),
        setting("paimbnails.levelfilters.browser", "My Levels Filters",
                "Filter your created levels by length, song and more.",
                "editor-filters-enable", "Search", S::Browser, true),

        saved("paimbnails.levelbackground.level", "Level Info Background",
              "Thumbnail based background on the level info screen.",
              "module-levelinfo-bg", "Visual", S::Level, true),
        setting("paimbnails.dynamicsong.level", "Dynamic Song",
                "Plays the level song while browsing its info.",
                "dynamic-song", "Audio", S::Level, true),
        setting("paimbnails.imagewarning.level", "Image Object Warning",
                "Warns when a level contains a watermarked image or GIF made from objects.",
                "image-watermark-warning-enable", "Safety", S::Level, true),
        saved("paimbnails.officialslots.level", "Official Slots",
              "Editable cosmetic levels in the official list: any id or .gmd, painted difficulty and stars.",
              "module-official-slots", "Visual", S::Level, true),

        // Info Suite — master first
        setting(kInfoSuite, "Info Suite",
                "Master switch for every info and history module.",
                "info-suite-enable", "Master", S::Info, true),

        infoMod("paimbnails.extendedinfo.info", "Extended Level Info",
                "Redesigns the two info popups of a level: your stats with charts, and every hidden field.",
                "info-mod-extended", "Level", true),
        infoMod("paimbnails.visibleids.info", "Visible IDs",
                "Level, list, comment and user ids at a glance.",
                "info-mod-ids", "Level", true),

        infoMod("paimbnails.jumptopage.info", "Jump To Page",
                "Jump to any browser page, with no 999 cap.",
                "info-mod-jump-page", "Browsing", true),
        infoMod("paimbnails.advancedsearch.info", "Advanced Search",
                "Filter by id range, game version, object count and more.",
                "info-mod-advanced-search", "Browsing", true),
        infoMod("paimbnails.searchpresets.info", "Search Presets",
                "Save and reload named filter sets.",
                "info-mod-search-presets", "Browsing", true,
                "paimbnails.advancedsearch.info"),

        infoMod("paimbnails.progresstracking.info", "Progress Tracking",
                "Attempts, jumps and deaths recorded per level.",
                "info-mod-progress", "Progress", true),
        infoMod("paimbnails.deathheatmap.info", "Death Heatmap",
                "Shows where you die most along the level.",
                "info-mod-death-heatmap", "Progress", true,
                "paimbnails.progresstracking.info"),

        infoMod("paimbnails.unregprofiles.info", "Unregistered Profiles",
                "Opens profiles for green, account-less users.",
                "info-mod-unreg-profiles", "Social", true),
        infoMod("paimbnails.commenttools.info", "Comment Tools",
                "Jump to comment page, comment ids and exact dates.",
                "info-mod-comment-tools", "Social", true),
        infoMod("paimbnails.greenusers.info", "Fix Green Usernames",
                "Fills in usernames the game failed to resolve.",
                "info-mod-green-users", "Social", true),

        infoMod("paimbnails.gdhistory.info", "GDHistory Enrichment",
                "Opt-in: exact dates, names and recorded level history from history.geometrydash.eu.",
                "info-mod-gdhistory", "Data", false),

        saved("paimbnails.performance.gameplay", "Performance Mode",
              "Improves FPS with configurable CPU, GPU and visual cuts.",
              "module-performance", "Performance", S::Gameplay, false),
        saved("paimbnails.nativeperf.gameplay", "Native Performance Mode",
              "Uses Geometry Dash's built-in performance mode.",
              "module-performance-native", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.glowcut.gameplay", "Disable Glow",
              "Stops object glow from being created.",
              "module-performance-glow", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.bgeffects.gameplay", "Disable Background Effects",
              "Turns off extra background effects while playing.",
              "module-performance-bg-effects", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.gameeffects.gameplay", "Disable Gameplay Effects",
              "Turns off gravity and glitter effects.",
              "module-performance-game-effects", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.playereffects.gameplay", "Disable Player Effects",
              "Turns off trails, streaks and player particles.",
              "module-performance-player-effects", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.dynamicvolume.gameplay", "Pause Dynamic Volume",
              "Pauses Dynamic Volume analysis and DSP during gameplay.",
              "module-performance-dynamic-volume", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.modvisuals.gameplay", "Disable Paimbnails Effects",
              "Pauses the pet, custom progress bar, death effects and pause zoom.",
              "module-performance-mod-visuals", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.autopreview.gameplay", "Disable Auto Preview",
              "Stops automatic thumbnail capture while playing.",
              "module-performance-auto-preview", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.perftransitions.gameplay", "Disable Level Transitions",
              "Skips custom entry and exit transitions.",
              "module-performance-transitions", "Performance", S::Gameplay, true, kPerformance),
        saved("paimbnails.backgroundcut.gameplay", "Hide Background",
              "Hides the background and middleground.",
              "module-performance-background", "Visual Cuts", S::Gameplay, false, kPerformance),
        saved("paimbnails.groundcut.gameplay", "Hide Ground",
              "Hides both ground layers.",
              "module-performance-ground", "Visual Cuts", S::Gameplay, false, kPerformance),
        saved("paimbnails.decocut.gameplay", "Hide Decoration",
              "Hides objects marked as decoration.",
              "module-performance-decoration", "Visual Cuts", S::Gameplay, false, kPerformance),
        saved("paimbnails.gradientcut.gameplay", "Disable Gradients",
              "Stops gradient layers from updating or drawing.",
              "module-performance-gradients", "Visual Cuts", S::Gameplay, false, kPerformance),
        saved("paimbnails.shadercut.gameplay", "Disable Shaders",
              "Stops gameplay shader updates.",
              "module-performance-shaders", "Visual Cuts", S::Gameplay, false, kPerformance),
        saved("paimbnails.particlecut.gameplay", "Disable Particles",
              "Stops level particle systems from updating or drawing.",
              "module-performance-particles", "Visual Cuts", S::Gameplay, false, kPerformance),
        saved("paimbnails.levelcut.gameplay", "Disable Flashes and Waves",
              "Hides flash, glow and circle-wave effects.",
              "module-performance-level-effects", "Visual Cuts", S::Gameplay, false, kPerformance),
        setting("paimbnails.capture.gameplay", "Thumbnail Capture",
                "Capture button and keybind to shoot thumbnails.",
                "enable-thumbnail-taking", "Capture", S::Gameplay, true),
        custom("paimbnails.progressbar.gameplay", "Custom Progress Bar",
               "Restyle, move and animate the progress bar.", "HUD", S::Gameplay, false),
        setting("paimbnails.goldenbest.gameplay", "Golden Best",
                "Turns the percentage gold while beating your record.",
                "golden-best-enabled", "HUD", S::Gameplay, true),
        saved("paimbnails.deatheffects.gameplay", "Death Effects",
              "Custom effects when the player dies.",
              "module-death-effects", "Effects", S::Gameplay, true),
        custom("paimbnails.levelentry.gameplay", "Level Entry Effects",
               "Effects when entering and leaving a level.", "Effects", S::Gameplay, true),
        saved("paimbnails.pausezoom.gameplay", "Pause Zoom",
              "Zoom and hide the pause menu with keybinds.",
              "module-pause-zoom", "HUD", S::Gameplay, true),
        custom("paimbnails.frameinterp.gameplay", "Frame Interpolation",
               "Draws between physics ticks so movement stays smooth at any refresh rate.",
               "Motion", S::Gameplay, false),

        setting("paimbnails.profileredesign.profile", "Profile Redesign",
                "Modern layout for the profile page.",
                "profile-redesign-enabled", "Layout", S::Profile, true),
        setting("paimbnails.profilemusic.profile", "Profile Music",
                "Custom music while viewing profiles.",
                "profile-music-enabled", "Audio", S::Profile, true),
        saved("paimbnails.paimonprofiles.profile", "Paimon Profiles",
              "Profile pictures, reviews, ratings and views.",
              "module-profiles", "Social", S::Profile, true),
        setting("paimbnails.globalicons.profile", "Global Icons",
                "Shows other players' custom icons on their profile.",
                "global-icons-enabled", "Social", S::Profile, true),
        saved("paimbnails.badges.profile", "Role Badges",
              "Paimbnails role badges next to names.",
              "module-badges", "Social", S::Profile, true),
        saved("paimbnails.progression.profile", "Profile Levels",
              "XP, levels and badges built from public stats, on every profile.",
              "module-progression", "Social", S::Profile, true),
        saved("paimbnails.iconcopy.profile", "Copy Icons",
              "Copy someone's icon set from their profile and wear it from the garage.",
              "module-icon-copy", "Social", S::Profile, true),

        // Social — comments and messages
        saved("paimbnails.emotes.social", "Emotes",
              "Emote picker and rendering in comments.",
              "module-emotes", "Comments", S::Social, true),
        saved("paimbnails.fonts.social", "Comment Fonts",
              "Font tags and picker for comments.",
              "module-fonts", "Comments", S::Social, true),
        setting("paimbnails.mentions.social", "Comment Mentions",
                "Notifies you when someone mentions you.",
                "mentions-enabled", "Comments", S::Social, false),
        setting("paimbnails.messagesredesign.social", "Messages Redesign",
                "Reworked message list and reader.",
                "messages-redesign-enabled", "Messages", S::Social, true),
        setting("paimbnails.messagenotifs.social", "Message Notifications",
                "Alerts for new messages and friend requests.",
                "msgnotif-enabled", "Messages", S::Social, false),
        setting("paimbnails.thumbalerts.social", "New Thumbnail Alerts",
                "Announces thumbnails that just went live, over the thumbnail itself.",
                "thumbalert-enabled", "Thumbnails", S::Social, true),
        saved("paimbnails.thumbrequests.social", "Thumbnail Requests",
              "The requests filed from Discord and what the team decided about each one.",
              "module-thumb-requests", "Thumbnails", S::Social, true),

        setting("paimbnails.colorpicker.editor", "Colorpicker",
                "Eyedropper to pick colors anywhere in the editor.",
                "editor-color-picker-enable", "Tools", S::Editor, true),
        setting("paimbnails.gifimport.editor", "GIF to Objects",
                "Imports GIFs, videos and images as optimized native objects and triggers, with a free mode that draws with the whole decoration library.",
                "gif-import-enable", "Tools", S::Editor, true),
        setting("paimbnails.gifrender.editor", "Render Import",
                "Refines curves in repeated passes and builds objects in the background.",
                "gif-render-enable", "Tools", S::Editor, true,
                "paimbnails.gifimport.editor"),
        setting("paimbnails.physics.editor", "Physics Lab",
                "Simulates compound bodies and bakes their motion into native triggers.",
                "editor-physics-enable", "Tools", S::Editor, true),
        setting("paimbnails.editormusic.editor", "Editor Music",
                "Music player in the editor that pauses itself while you playtest.",
                "editor-music-enable", "Tools", S::Editor, true),
        setting("paimbnails.collab.editor", "Collab Editor",
                "Real time collaborative editing.",
                "collab-enabled", "Collab", S::Editor, true),
        setting("paimbnails.collabcursors.editor", "Collab Cursors",
                "Shows collaborators' custom cursors.",
                "collab-custom-cursors", "Collab", S::Editor, true,
                "paimbnails.collab.editor"),
        setting("paimbnails.inputscroll.editor", "Input Scroll",
                "Scroll the wheel over numeric inputs to change them.",
                "input-scroll-enable", "Input", S::Editor, true),
        setting("paimbnails.songsearch.editor", "Song Search",
                "Type a song name in the song id box.",
                "song-search-enable", "Tools", S::Editor, true),

        setting("paimbnails.autoupdate.system", "Auto Update",
                "Downloads and installs updates on exit.",
                "auto-update", "Updates", S::System, false),
        setting("paimbnails.diskcache.system", "Disk Cache",
                "Keeps thumbnails on disk to avoid redownloads.",
                "enable-disk-cache", "Cache", S::System, true),
        setting("paimbnails.robtopcache.system", "RobTop Response Cache",
                "Caches Geometry Dash server responses.",
                "gd-robtop-cache-enabled", "Cache", S::System, true),
        setting("paimbnails.discordrpc.system", "Discord Rich Presence",
                "Shows your activity on your Discord profile.",
                "discord-rpc-enabled", "Integrations", S::System, true),
        saved("paimbnails.moderation.system", "Moderation Tools",
              "Reports, bans and verification for staff.",
              "module-moderation", "Staff", S::System, true),
        saved("paimbnails.modauth.system", "Secure Mod Code",
              "Provisions and rotates the credential used by staff tools.",
              "module-mod-auth", "Staff", S::System, true,
              "paimbnails.moderation.system"),
        setting("paimbnails.debuglogs.system", "Debug Logs",
                "Verbose logging for troubleshooting.",
                "enable-debug-logs", "Diagnostics", S::System, false),
        setting("paimbnails.crashreports.system", "Crash Reports",
                "Sends the Geode crash log to the developers after a crash.",
                "crash-reports-enable", "Diagnostics", S::System, false),
    };
}

} // namespace

std::vector<Module> const& all() {
    static std::vector<Module> const kCatalog = buildCatalog();
    return kCatalog;
}

} // namespace paimon::modules
